### ISSUE TITLE
Make the output folders permisions easier to modify

### ISSUE THREAD

**Issue by micahjohnson150** [USDA-ARS-NWRC/basin_setup#17]
@etrujil  would like the permissions on the output folders to not be protected. I agree it is annoying.

@micah-prime just figured out how to do this for our other repos. The solution should be as follows:

Add the following line to the docker file.
RUN echo "umask 0002" >> /etc/bash.bashrc

This simply changes the user permissions mask from 0022 which is user can  READ/WRITE the group can READ and everyone else can READ aka (-rw-r-r-) to  0002 aka (-rw-rw-r-)

**Comment by micah-prime** [comment]
Additionally, "umask 0002" can be put into the docker_entrypoint.sh script if an entrypoint script is used in the dockerfile. 

The "umask 0002" in the bashrc works for any docker run with the "-i" (interactive) flag, but does not work without the flag, which is why it would be necessary to put the umask call in the entrypoint.
